### PR TITLE
Bug fix - PHP7 warnings

### PR DESCRIPTION
**Pull request by garethellis36**
Replaces #19 as a way of addressing issue with warnings in PHP7.

### CODE REVIEW

**Comment by jeremykendall** [comment]
Beautiful! Thanks so much!

**Comment by garethellis36** [comment]
Please ping me when you do a new release so I can update my composer.json with the new version :)

**Comment by jeremykendall** [comment]
:+1:

**Comment by jeremykendall** [comment]
@garethellis36 Done! https://github.com/jeremykendall/password-validator/releases/tag/3.0.4

Since it's just a bugfix release, you may not even have to update your composer.json.

**Comment by garethellis36** [comment]
:+1:

**Pull request merged**
